Portal_FilmShooting/Portal_FilmShooting/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    re_path('^', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('booking/', include(('booking_places.urls', 'booking_places'), namespace='booking_places')),
]

Portal_FilmShooting/accounts/urls.py
from . import views
from django.conf import settings
from django.urls import path, re_path


urlpatterns = [
	re_path(r'^$', views.index, name='index'),
	re_path(r'^index/$', views.index, name='index'),
	re_path(r'^login/$', views.login_view, name='login_view'),
	re_path(r'^logout/$', views.logout_view, name='logout_view'),
	re_path(r'^register/$', views.register, name='register'),
	re_path(r'^profiledpdn/$', views.profile_view, name='profile_view'),
	re_path(r'^profile/$', views.view_profile, name='view_profile'),
    re_path(r'^profile/(?P<pk>\d+)/$', views.view_profile, name='view_profile_with_pk'),
    re_path(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    re_path(r'^change-password/$', views.change_password, name='change_password'),
	
]

Portal_FilmShooting/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class Profile(models.Model):
	ACCESS_OPTIONS = (
		('Admin', 'Admin'),
		('Client', 'Client'),
		('Customer', 'Customer'),
		)
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	access = models.CharField(max_length=10, choices=ACCESS_OPTIONS, null=False)
	
	def __str__(self):
		return self.user.username


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=100, default='')

    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

Portal_FilmShooting/accounts/forms.py
from django import forms
from django.forms import ModelForm
from accounts.models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


from accounts.models import UserProfile


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user



class LoginForm(forms.Form):
	ACCESS_OPTIONS = (
		('Admin', 'Admin'),
		('Client', 'Client'),
		('Customer', 'Customer'),
		)
	username = forms.CharField(label='username', max_length=100)
	password = forms.CharField(widget=forms.PasswordInput())


class EditProfileForm(UserChangeForm):
    template_name='/something/else'

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password'
        )

Portal_FilmShooting/accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse

from accounts.forms import (
    RegistrationForm,
    EditProfileForm,
    LoginForm,

)

from .models import Profile
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required



def index(request):
	return render(request, 'accounts/index.html')


def register(request):
	if request.method == 'POST':
		form = RegistrationForm(request.POST)
		if form.is_valid():
			user = form.save()
			user.refresh_from_db
			#user.profile.access = form.cleaned_data.get('access')
			user.save()
			return render(request, 'accounts/login.html')

	else:
		form = RegistrationForm()

	args = {'form' : form}
	return render(request, 'accounts/reg_form.html', args)



def login_view(request):
	if request.method == 'POST':
		form = LoginForm(request.POST)
		if form.is_valid():
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user = authenticate(request, username=username, password=password)
			if user is not None:
				login(request, user)
				return render(request, 'accounts/index.html')

			else:
				return HttpResponse("Invalid login essentials", {})
	else:
		form = LoginForm()

	return render(request, 'accounts/login.html', {'form': form})


@login_required
def logout_view(request):
    logout(request)
    return redirect('/')


@login_required
def profile_view(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request, 'accounts/profiledpdn.html', args)


@login_required
def view_profile(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request, 'accounts/profile.html', args)


@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:view_profile'))
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse('accounts:view_profile'))
        else:
            return redirect(reverse('accounts:change_password'))
    else:
        form = PasswordChangeForm(user=request.user)

        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)

Portal_FilmShooting/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}


{% block head %}
<title>Profile</title>
{% endblock %}

{% block content %}

<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
			<form class="login100-form validate-form" action="" method="post">
  					<span class="login100-form-title p-b-26">
						Change Password
					</span><br><br>

        {% csrf_token %}
        <p><label for="id_old_password">Old password:</label> <input type="password" name="old_password" required id="id_old_password" autofocus /></p>
        <br>
		<p><label for="id_new_password1">New password:</label> <input type="password" name="new_password1" required id="id_new_password1" /> <span class="helptext"></span></p>
		<br>
		<p><label for="id_new_password2">New password confirmation:</label> <input type="password" name="new_password2" required id="id_new_password2" /></p>

		<br>
        <div class="container-login100-form-btn">
							<div class="wrap-login100-form-btn">
								<div class="login100-form-bgbtn"></div>
								<button type="submit" class="login100-form-btn">Save</button>
							</div>
						</div> 
    </form>
    <br>
</div>

{% endblock %}

Portal_FilmShooting/accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% block content %}




<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
			<form class="login100-form validate-form" action="" method="post">
  					<span class="login100-form-title p-b-26">
						Edit Profile
					</span><br><br>

      					{% csrf_token %}
       					 <p><label for="id_email">Email address:</label> <input type="email" name="email" value="harshngu210@gmail.com" id="id_email" maxlength="254" /></p>
       					 	<br>
							<p><label for="id_first_name">First name:</label> <input type="text" name="first_name" value="Harsh" id="id_first_name" maxlength="30" /></p>
							<br>
							<p><label for="id_last_name">Last name:</label> <input type="text" name="last_name" value="Gupta" id="id_last_name" maxlength="150" /></p>
							<br>
							<p><label for="id_password">Password:</label> <div id="id_password">

						 <strong>No password set.</strong>

						</div> <span class="helptext">Raw passwords are not stored, so there is no way to see this user's password, but you can change the password using <a href="../password/">this form</a>.</span></p>

							<div class="container-login100-form-btn">
							<div class="wrap-login100-form-btn">
								<div class="login100-form-bgbtn"></div>
								<button type="submit" class="login100-form-btn">Save</button>
							</div>
						</div> 


       				
   				 </form>
   				 <br>
			</div>
			</div>
			</div>


{% endblock %}

Portal_FilmShooting/accounts/templates/accounts/index.html
{% extends 'base.html' %}

{% block content %}
	{% load static %}
	<link rel="stylesheet" href="{% static 'accounts/imageoverlay.css' %}" type="text/css">
	<link href="{% static 'accounts/carousel.css' %}" rel="stylesheet">

	<div id="myCarousel" class="carousel slide" data-ride="carousel">
		<!-- Indicators -->
		<ol class="carousel-indicators">
			<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
			<li data-target="#myCarousel" data-slide-to="1"></li>
			<li data-target="#myCarousel" data-slide-to="2"></li>
		</ol>
		<div class="carousel-inner" role="listbox">
			<div class="item active">
				<img class="first-slide" src="{% static 'accounts/img/Akshardham.jpg' %}" alt="First slide">
				<div class="container">
					<div class="carousel-caption">
						<h1 style="font-size: 100px;">Akshardham</h1>
						<p style="font-size: 60px; color:#fff">A Maginificent temple</p>
						<p style="font-size: 60px;"><a style="font-size: 40px;" class="btn btn-lg btn-primary" href="/login" role="button">Book location</a></p>
					</div>
				</div>
			</div>
			<div class="item">
				<img class="second-slide" src="{% static 'accounts/img/IndiaGate.jpg' %}" alt="Second slide">
				<div class="container">
					<div class="carousel-caption">
						<h1 style="font-size: 100px;">India Gate</h1>
						<p style="font-size: 60px; color:#fff">India Gate Monument</p>
						<p style="font-size: 60px;"><a style="font-size: 40px;" class="btn btn-lg btn-primary" href="/login" role="button">Book location</a></p>
					</div>
				</div>
			</div>
			<div class="item">
				<img class="third-slide" src="{% static 'accounts/img/LotusTemple.jpg' %}" alt="Third slide">
				<div class="container">
					<div class="carousel-caption">
						<h1 style="font-size: 100px;">Lotus Temple</h1>
						<p style="font-size: 60px; color:#fff">A Maginificent temple</p>
						<p style="font-size: 60px;"><a style="font-size: 40px;" class="btn btn-lg btn-primary" href="/login" role="button">Book location</a></p>
					</div>
				</div>
			</div>
			 <div class="item">
				<img class="fourth-slide" src="{% static 'accounts/img/LodiGarden.jpg' %}" alt="Second slide">
				<div class="container">
					<div class="carousel-caption">
						<!-- <h1>Another example headline.</h1> -->
						<!-- <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p> -->
						<!-- <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p> -->
					</div>
				</div>
			</div>
			<div class="item">
				<img class="fifth-slide" src="{% static 'accounts/img/HumayunsTomb.jpg' %}" alt="Second slide">
				<div class="container">
					<div class="carousel-caption">
						<!-- <h1>Another example headline.</h1> -->
						<!-- <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p> -->
						<!-- <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p> -->
					</div>
				</div>
			</div>
			</div>
		<a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
			<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
			<span class="sr-only">Previous</span>
		</a>
		<a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
			<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		</a>
	</div><!-- /.carousel -->


<div class="container marketing">
	<hr class="featurette-divider" data-aos="fade-up">
	<h1 style="text-align:center;">How It Works</h1>


	<div class="row featurette" >

		<div class="col-md-7">
			<h5 class="featurette-heading">Step 1<br><span class="text-muted" style="font-size: 50px; color:#0762a3">Login/Registration</span></h2>
			<p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
		</div>
		<div class="col-md-5" >
			<img class="featurette-image img-responsive center-block" src="{% static 'accounts/img/rl.png' %}" alt="Generic placeholder image">
		</div>
	</div>

	<hr class="featurette-divider">

	<div class="row featurette" data-aos="fade-up">
		<div class="col-md-7 col-md-push-5" >
			<h2 class="featurette-heading">Step 2<br><span class="text-muted" style="font-size: 50px; color:#0762a3">Fill Application Form</span></h2>
			<p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
		</div>
		<div class="col-md-5 col-md-pull-7" data-aos="fade-up">
			<img style="border-radius:50%;" class="featurette-image img-responsive center-block" src="{% static 'accounts/img/fa.jpg' %}" alt="Generic placeholder image" height=380 width=380>
		</div>
	</div>

	<hr class="featurette-divider">

	<div class="row featurette" data-aos="fade-up">
		<div class="col-md-7" >
			<h2 class="featurette-heading">Step 3<br><span class="text-muted" style="font-size: 50px; color:#0762a3">Make Payment</span></h2>
			<p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
		</div>
		<div class="col-md-5" >
			<img class="featurette-image img-responsive center-block" src="{% static 'accounts/img/mp.png' %}" alt="Generic placeholder image">
		</div>
	</div>

	<hr class="featurette-divider" style="margin: 30px 0;">
	<h1 style="text-align:center; margin-bottom: 20px; color:#0762a3;">Movies</h1>

	<div class="row">
		<div class="col-lg-4" data-aos="fade-up">
			<img class="img-circle" src="{% static 'accounts/img/m1.jpg' %}" alt="Generic placeholder image" width="140" height="140">
			<h2>Shoot At Delhi<br>(Red Fort)</h2>

			<p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
		</div><!-- /.col-lg-4 -->
		<div class="col-lg-4" data-aos="fade-up">
			<img class="img-circle" src="{% static 'accounts/img/m2.jpg' %}" alt="Generic placeholder image" width="140" height="140">
			<h2>Shoot At Delhi<br>(Hauz Khas Fort)</h2>

			<p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
		</div><!-- /.col-lg-4 -->
		<div class="col-lg-4" data-aos="fade-up">
			<img class="img-circle" src="{% static 'accounts/img/m3.jpg' %}" alt="Generic placeholder image" width="140" height="140">
			<h2>Shoot At Delhi<br>(Jama Masjid)</h2>

			<p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
		</div><!-- /.col-lg-4 -->
		<div class="col-lg-4" data-aos="fade-up">
			<img class="img-circle" src="{% static 'accounts/img/m4.jpg' %}" alt="Generic placeholder image" width="140" height="140">
			<h2>Shoot At Delhi<br>(Nehru Market)</h2>

			<p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
		</div>
		<div class="col-lg-4" data-aos="fade-up">
			<img class="img-circle" src="{% static 'accounts/img/m5.jpeg' %}" alt="Generic placeholder image" width="140" height="140">
			<h2>Shoot At Delhi<br>(Jama Masjid)</h2>

			<p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
		</div>
		<div class="col-lg-4" data-aos="fade-up">
			<img class="img-circle" src="{% static 'accounts/img/cdi.jpg' %}" alt="Generic placeholder image" width="140" height="140">
			<h2>Shoot At Delhi<br>(Connaught Place)</h2>

			<p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
		</div>
	</div>


<!--locations1-->
<hr width=1px>
<hr class="featurette-divider" style="margin: 80px 0;">
<h1 style="text-align:center; margin-bottom: 20px; color:#0762a3;">Locations</h1>
<div class="row" data-aos="fade-up">
  <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
    <div class="hovereffect">
        <img class="img-responsive" src="{% static 'accounts/img/17.jpg' %}" alt="" height=400 width=400 >
        <div class="overlay">
           <h2>JNU</h2>
        </div>
    </div>
	</div>
	<div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
	    <div class="hovereffect">
	        <img class="img-responsive" src="{% static 'accounts/img/21.jpg' %}" alt="" >
	        <div class="overlay">
	           <h2>Garden of Five Senses</h2>
	        </div>
	    </div>
	</div>
	<div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
	    <div class="hovereffect">
	        <img class="img-responsive" src="{% static 'accounts/img/10.jpg' %}" alt="" >
	        <div class="overlay">
	           <h2>Quitab Minar</h2>
	        </div>
	    </div>
	</div>
	<div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
	    <div class="hovereffect">
	        <img class="img-responsive" src="{% static 'accounts/img/12.jpg' %}" alt="">
	        <div class="overlay">
	           <h2>Jama Masjid</h2>
	        </div>
	    </div>
	</div>
</div>
<!-- /.col-lg-4 -->
<hr width=2px color=blue>
<hr class="featurette-divider">
      <!-- /END THE FEATURETTES -->
</div><!-- /.container -->
{% endblock %}

{% block javascript %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>

<script src="{% static 'accounts/dist/js/bootstrap.min.js' %}"></script>
<!-- Just to make our placeholder images work. Don't actually copy the next line! -->
<script src="{% static 'accounts/assets/js/vendor/holder.min.js' %}"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="{% static 'accounts/assets/js/ie10-viewport-bug-workaround.js' %}"></script>
<script>
AOS.init();
</script>
{% endblock %}

Portal_FilmShooting/accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% block content %}
<div class="container" style="width: 50%; height: 70%;">
<div class="jumbotron">
  <h1 class="display-6">Logged out</h1>
</div>
</div>
{% endblock %}

Portal_FilmShooting/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block nav %}



<div class="dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" id="menu1" data-toggle="dropdown">
    <span class="caret"></span>Profile</button>
    <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
      <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'accounts:view_profile' %}">View Profile</a></li>
      <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'accounts:edit_profile' %}">Edit </a></li>
      <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'accounts:change_password' %}">Change Password</a></li>
      <li role="presentation" class="divider"></li>
      
    </ul>
  </div>
{% endblock %}

{% block content %}

        <div class="container-login100">
            <div class="wrap-login100">
            
                    <span class="login100-form-title p-b-26">
                        User Profile
                    </span><br><br>
        <li><a href="#"><span ></span> Welcome{{ request.user.first_name }}</a>
    <p>Username: {{ user }}
    <p>First name: {{ request.user.first_name }}</p>
    <p>Last name: {{ request.user.last_name }}</p>
    <p>Email: {{ request.user.email }}</p>

</div>
            </div>
          :

{% endblock %}

Portal_FilmShooting/accounts/templates/accounts/profiledpdn.html
{% extends 'base.html' %}

{% block nav %}

<div class="dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" id="menu1" data-toggle="dropdown">
    <span class="caret"></span></button>
    <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
      <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'accounts:view_profile' %}">View Profile</a></li>
      <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'accounts:edit_profile' %}">Edit </a></li>
      <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'accounts:change_password' %}">Change Password</a></li>
      <li role="presentation" class="divider"></li>
      <li role="presentation"><a role="menuitem" tabindex="-1" href="#">About Us</a></li>
    </ul>
  </div>
{% endblock %}

Portal_FilmShooting/accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}
{% block content %}

<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
					<form class="login100-form"  method="post">

					<span class="login100-form-title p-b-26">
						Register
					</span>
					<br>
					
					{% csrf_token %}
					

						<div class="wrap-input100 validate-input" >
								<input class="input100" id="id_username" required maxlength="150" type="text" name="username" value="">
								<span class="focus-input100" data-placeholder="Username"></span>
						 </div>
						 <div class="wrap-input100 validate-input" >
								<input class="input100" id="id_first_name" maxlength="30" type="text" name="first_name"value="">
								<span class="focus-input100" data-placeholder="first name"></span>
						 </div>
						 <div class="wrap-input100 validate-input" >
								<input class="input100" id="id_last_name" maxlength="150" type="text" name="last_name" value="">
								<span class="focus-input100" data-placeholder="last name"></span>
						 </div>

						 <div class="wrap-input100 validate-input" >
								<input class="input100" required id="id_email" type="text" name="email" value="">
								<span class="focus-input100" data-placeholder="email"></span>
						 </div>
						 <div class="wrap-input100 validate-input" >
								<input class="input100" required id="id_password1" type="password" name="password1"  value="">
								<span class="focus-input100" data-placeholder="Password"></span>
						 </div>
						 <div class="wrap-input100 validate-input" >
								<input class="input100"  required id="id_password2" type="password" name="password2"value="">
								<span class="focus-input100" data-placeholder="Confirm Password"></span>
						 </div>

						 <div class="container-login100-form-btn">
							<div class="wrap-login100-form-btn">
								<div class="login100-form-bgbtn"></div>
								<button type="submit" class="login100-form-btn">Submit</button>
							</div>
						</div>
				</form>

			</div>
		</div>
</div>



<!--
<div class="container" style="width: 70%; height: 70%;">
<div class="jumbotron">


  <h1 class="display-4">Register</h1>
	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}

						<p><label for="id_username">Username:</label> <input type="text" name="username" id="id_username" required maxlength="150" autofocus /> <span class="helptext"></span></p>

						<p><label for="id_first_name">First name:</label> <input type="text" name="first_name" id="id_first_name" maxlength="30" /></p>

						<p><label for="id_last_name">Last name:</label> <input type="text" name="last_name" id="id_last_name" maxlength="150" /></p>
						<p><label for="id_email">
							
						</label for="id_email">Email:</label><input type="email" name="email" required id="id_email" /></p>

						<p><label for="id_password1">Password:</label> <input type="password" name="password1" required id="id_password1" /> <span class="helptext"></span></p>

						<p><label for="id_password2">Password confirmation:</label> <input type="password" name="password2" required id="id_password2" /> <span class="helptext"></span></p>




    					<input class="input100" id="password" type="password" placeholder="Password" name="password" value="">
		<button type="submit" class="btn btn-primary">Submit</button>
	</form>
</div>
</div>
<form class="login100-form"  method="post">

					<span class="login100-form-title p-b-26">
						Register
					</span>
					<br>
					{% csrf_token %}
					
						<div class="wrap-input100 validate-input" >
								<input class="input100" id="username" type="text" name="username" value="">
								<span class="focus-input100" data-placeholder="Username"></span>
						 </div>
						 <div class="wrap-input100 validate-input" >
								<input class="input100" id="first_name" type="text" name="first_name"value="">
								<span class="focus-input100" data-placeholder="first name"></span>
						 </div>
						 <div class="wrap-input100 validate-input" >
								<input class="input100" id="last_name" type="text" name="last_name" value="">
								<span class="focus-input100" data-placeholder="last name"></span>
						 </div>
						 <div class="wrap-input100 validate-input" >
								<input class="input100" id="email" type="text" name="email" value="">
								<span class="focus-input100" data-placeholder="email"></span>
						 </div>
						 <div class="wrap-input100 validate-input" >
								<input class="input100" id="password" type="password" name="password" value="">
								<span class="focus-input100" data-placeholder="Password"></span>
						 </div>
						 <div class="wrap-input100 validate-input" >
								<input class="input100" id="password_cnf" type="password" name="password_cnf" value="">
								<span class="focus-input100" data-placeholder="Confirm Password"></span>
						 </div>
						 <div class="container-login100-form-btn">
							<div class="wrap-login100-form-btn">
								<div class="login100-form-bgbtn"></div>
								<button type="submit" class="login100-form-btn">Submit</button>
							</div>
						</div>
				</form>


-->
{% endblock %}

Portal_FilmShooting/accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Password reset</h1>
    <p>
        Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form>
</div>
{% endblock %}