Portal_FilmShooting/Portal_FilmShooting/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    re_path('^', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('booking/', include(('booking_places.urls', 'booking_places'), namespace='booking_places')),
]

Portal_FilmShooting/accounts/urls.py
from . import views
from django.conf import settings
from django.urls import path, re_path


urlpatterns = [
	re_path(r'^$', views.index, name='index'),
	re_path(r'^index/$', views.index, name='index'),
	re_path(r'^login/$', views.login_view, name='login_view'),
	re_path(r'^logout/$', views.logout_view, name='logout_view'),
	re_path(r'^register/$', views.register, name='register'),
	re_path(r'^profiledpdn/$', views.profile_view, name='profile_view'),
	re_path(r'^profile/$', views.view_profile, name='view_profile'),
    re_path(r'^profile/(?P<pk>\d+)/$', views.view_profile, name='view_profile_with_pk'),
    re_path(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    re_path(r'^change-password/$', views.change_password, name='change_password'),
	
]

Portal_FilmShooting/booking_places/urls.py
from . import views
from django.conf import settings
from django.urls import path, re_path


urlpatterns = [
	re_path(r'^$', views.home, name='home'),
	re_path(r'^submit_application_form/', views.application_form, name='application_form'),
	# re_path(r'^check_application/$', views.check_application, name='check_application'),
	re_path(r'^select_locations/$', views.render_select_locations, name='select_locations'),
	re_path(r'^check_dates/$', views.check_dates, name='check_dates'),
	re_path(r'^submit_application_location_form/', views.application_location_form, name='application_location_form'),
	re_path(r'^payment_result/', views.payment_result, name='payment_result'),
	re_path(r'^dashboard/', views.dashboard, name='dashboard'),
	re_path(r'^check_application/(?P<application_id>\d+)/$', views.check_application, name='check_application'),
]

Portal_FilmShooting/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class Profile(models.Model):
	ACCESS_OPTIONS = (
		('Admin', 'Admin'),
		('Client', 'Client'),
		('Customer', 'Customer'),
		)
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	access = models.CharField(max_length=10, choices=ACCESS_OPTIONS, null=False)
	
	def __str__(self):
		return self.user.username


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=100, default='')

    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

Portal_FilmShooting/booking_places/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User


class Location(models.Model):
    name = models.CharField(max_length=100, default='')
    price = models.IntegerField()
    stakeholder = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Application(models.Model):
    producer = models.ForeignKey(User, on_delete=models.CASCADE)
    film = models.CharField(max_length=100)
    production_house = models.CharField(max_length=100, default='')
    production_house_address = models.CharField(max_length=300, default='')
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    contact = models.CharField(validators=[phone_regex], max_length=17,default='')
    local_line_producer = models.CharField(max_length=100, blank=True, default='')
    local_line_producer_address = models.CharField(max_length=300, blank=True, default='')
    director = models.CharField(max_length=100)
    cinematographer = models.CharField(max_length=100)
    art_director = models.CharField(max_length=100)
    script = models.FileField(upload_to='scripts/')
    undertaking = models.FileField(upload_to='undertaking/', default='')
    time_of_modification = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.film


class ApplicationLocation(models.Model):
    STATUS_CHOICES = (
         (1, 'pending'),
         (2, 'paymentRequired'),
         (3, 'approved'),
         (4, 'applicationRejected'),
         (5, 'modify'),
         (6, 'noPayment'),
        )

    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    application = models.ForeignKey(Application, on_delete=models.CASCADE)
    current_status = models.SmallIntegerField(choices=STATUS_CHOICES, default=1)
    shoot_start_date = models.DateField()
    shoot_end_date = models.DateField()
    remarks = models.CharField(max_length=200, null=True, blank=True)
    time_of_modification = models.DateTimeField(auto_now=True)
    time_of_creation = models.DateTimeField(auto_now_add=True)


class Payment(models.Model):
    payment_id = models.CharField(max_length=100)

Portal_FilmShooting/accounts/forms.py
from django import forms
from django.forms import ModelForm
from accounts.models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


from accounts.models import UserProfile


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user



class LoginForm(forms.Form):
	ACCESS_OPTIONS = (
		('Admin', 'Admin'),
		('Client', 'Client'),
		('Customer', 'Customer'),
		)
	username = forms.CharField(label='username', max_length=100)
	password = forms.CharField(widget=forms.PasswordInput())


class EditProfileForm(UserChangeForm):
    template_name='/something/else'

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password'
        )

Portal_FilmShooting/accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse

from accounts.forms import (
    RegistrationForm,
    EditProfileForm,
    LoginForm,

)

from .models import Profile
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required



def index(request):
	return render(request, 'accounts/index.html')


def register(request):
	if request.method == 'POST':
		form = RegistrationForm(request.POST)
		if form.is_valid():
			user = form.save()
			user.refresh_from_db
			#user.profile.access = form.cleaned_data.get('access')
			user.save()
			return render(request, 'accounts/login.html')

	else:
		form = RegistrationForm()

	args = {'form' : form}
	return render(request, 'accounts/reg_form.html', args)



def login_view(request):
	if request.method == 'POST':
		form = LoginForm(request.POST)
		if form.is_valid():
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user = authenticate(request, username=username, password=password)
			if user is not None:
				login(request, user)
				return render(request, 'accounts/index.html')

			else:
				return HttpResponse("Invalid login essentials", {})
	else:
		form = LoginForm()

	return render(request, 'accounts/login.html', {'form': form})


@login_required
def logout_view(request):
    logout(request)
    return redirect('/')


@login_required
def profile_view(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request, 'accounts/profiledpdn.html', args)


@login_required
def view_profile(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request, 'accounts/profile.html', args)


@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:view_profile'))
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse('accounts:view_profile'))
        else:
            return redirect(reverse('accounts:change_password'))
    else:
        form = PasswordChangeForm(user=request.user)

        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)

Portal_FilmShooting/accounts/templates/application_form.html
{% extends 'base.html' %}

{% block stylesheet %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'application_form/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'application_form/fonts/iconic/css/material-design-iconic-font.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'application_form/vendor/animate/animate.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'application_form/vendor/css-hamburgers/hamburgers.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'application_form/vendor/animsition/css/animsition.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'application_form/vendor/select2/select2.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'application_form/vendor/daterangepicker/daterangepicker.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'application_form/css/util.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'application_form/css/main.css' %}">
{% endblock %}

{% block content %}
	<div class="container-contact100">
		<div class="wrap-contact100">
			<form method="POST" action="/booking/submit_application_form/" class="contact100-form validate-form" enctype="multipart/form-data">
				<span class="contact100-form-title">
					Application Form
				</span>

				<label class="label-input100" for="message">Production House Name</label>
				<div class="wrap-input100 validate-input">
					<input id="message" class="input100" type="text" name="production_house" placeholder="XYZ Productions">
					<span class="focus-input100"></span>
				</div>

				<label class="label-input100" for="message">Production House Address</label>
				<div class="wrap-input100 validate-input">
					<textarea id="message" class="input100" name="production_house_address" placeholder="Sector 8-A Chandigarh"></textarea>
					<span class="focus-input100"></span>
				</div>

				<label class="label-input100" for="phone">Contact Number</label>
				<div class="wrap-input100">
					<input id="phone" class="input100" type="text" name="contact" placeholder="+91 800 000000">
					<span class="focus-input100"></span>
				</div>

				<label class="label-input100" for="first-name">Local Line Producer's Name</label>
				<div class="wrap-input100 validate-input">
					<input id="message" class="input100" type="text" name="local_line_producer" placeholder="John">
					<span class="focus-input100"></span>
				</div>

				<label class="label-input100" for="message">Local Line Producer's Address</label>
				<div class="wrap-input100 validate-input">
					<textarea id="message" class="input100" name="local_line_producer_address" placeholder="Address"></textarea>
					<span class="focus-input100"></span>
				</div>

				<label class="label-input100" for="message">Film Name</label>
				<div class="wrap-input100 validate-input">
					<input id="message" class="input100" type="text" name="film" placeholder="ABC">
					<span class="focus-input100"></span>
				</div>

				<label class="label-input100" for="message">Director's Name</label>
				<div class="wrap-input100 validate-input">
					<input id="message" class="input100" type="text" name="director" placeholder="XYZ">
					<span class="focus-input100"></span>
				</div>

				<label class="label-input100" for="message">Cinematographer's Name</label>
				<div class="wrap-input100 validate-input">
					<input id="message" class="input100" type="text" name="cinematographer" placeholder="XYZ">
					<span class="focus-input100"></span>
				</div>

				<label class="label-input100" for="email">Art Director's Name</label>
				<div class="wrap-input100 validate-input">
					<input id="message" class="input100" type="text" name="art_director" placeholder="XYZ">
					<span class="focus-input100"></span>
				</div>

				<label class="label-input100" for="email">Script</label>
				<div class="wrap-input100 validate-input">
					<input id="script" class="input100" type="file" name="script" placeholder="Script.pdf" accept="pdf">
					<span class="focus-input100"></span>
				</div>

				<label class="label-input100" for="email">Undertaking</label>
				<div class="wrap-input100 validate-input">
					<input id="undertaking" class="input100" type="file" name="undertaking" placeholder="Undertaking.pdf" accept="pdf">
					<span class="focus-input100"></span>
				</div>

				<div class="container-contact100-form-btn">
					<button class="contact100-form-btn">
						<span>
							Submit
							<i class="zmdi zmdi-arrow-right m-l-8"></i>
						</span>
					</button>
				</div>
			</form>
		</div>
	</div>
{% endblock %}

{% block javascript %}
	<script src="{% static 'application_form/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'application_form/vendor/animsition/js/animsition.min.js' %}"></script>
	<script src="{% static 'application_form/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'application_form/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'application_form/vendor/select2/select2.min.js' %}"></script>
	<script src="{% static 'application_form/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'application_form/vendor/daterangepicker/daterangepicker.js' %}"></script>
	<script src="{% static 'application_form/vendor/countdowntime/countdowntime.js' %}"></script>
	<script src="{% static 'application_form/js/main.js' %}"></script>
{% endblock %}

Portal_FilmShooting/accounts/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <title>SIH</title>

    <link href="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">
    <script src="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js"></script>
    <link href="{% static 'accounts/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'accounts/assets/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">
    <script src="{% static 'accounts/assets/js/ie-emulation-modes-warning.js' %}"></script>
    <link href="{% static 'accounts/carousel.css' %}" rel="stylesheet">

  {% block stylesheet %}
  {% endblock %}

{% load static %}
  <link rel="stylesheet" href="{% static 'accounts/lg.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'accounts/layout/styles/layout.css' %}" type="text/css">
  <title>Project Manager</title>
  </head>
  <body>
    <div class="navbar-wrapper">
      <div class="container">

        <nav class="navbar navbar-inverse navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">
                <img alt="Delhi Tourism" src="{% static 'accounts/assets/img/delhitourism.png' %}">
                Delhi Tourism
              </a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav navbar-right">
                <li><a href="/">Home</a></li>
                {% if user.is_authenticated %}
                  <ul class="nav navbar-nav">
                          <!-- <li><a href="{% url 'accounts:edit_profile' %}">Edit Profile</a></li> -->
                          <li> <a class="nav-item nav-link" href="{% url 'booking_places:home' %}">Application</a></li>
                          <li> <a class="nav-item nav-link" href="{% url 'booking_places:dashboard' %}">Dashboard</a></li>
                          <li> <a class="nav-item nav-link dropdown-toggle" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"href="{% url 'accounts:view_profile' %}">Hello! {{ request.user.first_name }}
                            <div class="dropdown">
  <ul class="dropdown-menu">
    <li><a href="{% url 'accounts:change_password' %}">Change Password</a></li>
    <li> <a class="nav-item nav-link" href="{% url 'accounts:logout_view' %}">Logout</a></li>
  </ul>
</div>
</a>
</li>

                  </div>
                {% else %}
                  <li>  <a class="nav-item nav-link" href="{% url 'accounts:login_view' %}">Login</a></li>
                  <li>  <a class="nav-item nav-link" href="{% url 'accounts:register' %}">Register</a></li>
              {% endif %}

              </ul>
            </div>
          </div>
        </nav>

      </div>
    </div>
</div>

  {% block content %}
  {% endblock %}


  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

  {% block javascript %}
  {% endblock %}
  </body>
  <footer height="100px">
    <p class="pull-right"><a href="#">Back to top</a></p>
    <p>&copy; 2018 Spartan &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
  </footer>
</html>

Portal_FilmShooting/accounts/templates/select_locations.html
{% extends 'base.html' %}

{% block stylesheet %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'location_form/vendor/bootstrap/css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'location_form/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'location_form/fonts/iconic/css/material-design-iconic-font.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'location_form/vendor/animate/animate.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'location_form/vendor/css-hamburgers/hamburgers.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'location_form/vendor/animsition/css/animsition.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'location_form/vendor/select2/select2.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'location_form/vendor/daterangepicker/daterangepicker.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'location_form/css/util.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'location_form/css/main.css' %}">

<link rel="stylesheet" href="{% static 'location_form/daterangepicker.min.css' %}">
<script src="{% static 'location_form/vendor/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'location_form/vendor/moment.min.js' %}" type="text/javascript"></script>

{% endblock %}

{% block content %}
<div class="container-contact100">
  <div class="wrap-contact100">
    <form id="original_form" action='' method='POST' class="contact100-form validate-form">
      <span class="contact100-form-title">
        Make Reservations
      </span>


      <div id="addItem"></div>


      <div class="container-contact100-form-btn" style="padding:50px">
      <a class="contact100-form-btn" onclick="addField()"><span style="color:white">
            Add another location
            <i class="zmdi zmdi-plus m-l-8"></i>
          </span></a>
      </div>

      <div class="container-contact100-form-btn">
        <button id='make_payment' class="contact100-form-btn">
          <span>
            Make Payment
            <i class="zmdi zmdi-arrow-right m-l-8"></i>
          </span>
        </button>
      </div>
    </form>
    <form style="display: none" id="custom_form" action="/booking/payment_result/" method="POST">
      <input id="custom_payment_input" name="payment_id" type="text" />
    </form>
  </div>
</div>
{% endblock %}

{% block javascript %}
	<script src="{% static 'location_form/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'location_form/vendor/animsition/js/animsition.min.js' %}"></script>
	<script src="{% static 'location_form/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'location_form/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'location_form/vendor/select2/select2.min.js' %}"></script>
	<script src="{% static 'location_form/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'location_form/vendor/daterangepicker/daterangepicker.js' %}"></script>
	<script src="{% static 'location_form/vendor/countdowntime/countdowntime.js' %}"></script>
	<script src="{% static 'location_form/js/main.js' %}"></script>
  <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
  <script>
  var disabledArr = ["04/12/2018", "04/13/2018", "04/14/2018", "04/30/2018", "04/31/2018", "05/01/2018", "05/02/2018"];

  var map = new Map();
  $('#make_payment').click(function(e) {
    e.preventDefault();
    submitForm(e);
  });

  function overlap_booking(id) {
    if (!map.has(id)) {
      map.set(id, false);
      return;
    }

    var daterangepicker = $(id).data('daterangepicker');
    var data = {
      'start_date': daterangepicker.startDate,
      'end_date': daterangepicker.endDate,
    };

    fetch('/booking/check_dates/',{
      body: JSON.stringify(data),
      method: 'POST',
      credentials: 'same-origin'
    }).then((response) => {
      response.json().then((data) => {
        var invalid = data['invalid'];
        var message = data['message'];
        map.set(id, invalid);
        $(`${id}-message`).html(message);
        var formInvalid = Array.from(map).reduce((accumulator = true, current_value) => accumulator & current_value[1]);
        $('#make_payment').prop('disabled', formInvalid[1]);
      });
    });
  }

  function submitForm(e) {
    e.preventDefault();

    var form = $("#original_form");
    var data = form.serializeArray();
    fetch('/booking/submit_application_location_form/', {
      body: JSON.stringify(data),
      method: 'POST',
      credentials: 'same-origin'
    }).then((response) => {
      var options = {
        "key": "rzp_test_uYI7kFmHMdcQPi",
        "amount": "50000", // 2000 paise = INR 20
        "name": "Delhi Tourism",
        "description": "Application processing fees by Delhi Tourism",
        "theme": {
          "color": "#F37254"
        },
        "handler": function (response){
          var id = response.razorpay_payment_id;
          var form = $('#custom_form');
          $('#custom_payment_input').value = id;
          form.submit();
        },
      };
      var rzp1 = new Razorpay(options);
      rzp1.open();
    });
}
  </script>

  <script>
  var newIDno = 0;
  function addField() {
  	var newID = "daterange" + newIDno;
  	var newIDWithHash = "#daterange" + newIDno;
    var addItem = `<div class="input50">
      <label class="label-input100" for="data-range0">
        Location *
      </label>
      <div class="wrap-input100 validate-input" style="display:inline-block;">
        <select class="input100" name="location" style="width: 100%;padding: 12px;border: 1px solid #ccc;border-radius: 4px;box-sizing: border-box;resize: vertical;" maxlength="100" id="id_location">
          {% for location in locations %}
          <option value="{{ location.id }}">{{ location.name }}</option>
          {% endfor %}
        </select>
        <span class="focus-input100"></span>
      </div>
      </div>
      <div class="input50">
        <label class="label-input100" for="p">Date</label>
        <div class="wrap-input100" style="display:inline-block;"  width="49%">
        <input id='${newID}' onchange="overlap_booking('${newIDWithHash}')" class="daterange000 input100" name="daterangepicker"/>
        <span class="focus-input100"></span></div></div>
      </div>
      <span id="${newID}-message"></span>
      `;
  	$("#addItem").append(addItem);
  	$(newIDWithHash).daterangepicker({
      isInvalidDate: function(arg){
          console.log(arg);
          var thisMonth = arg._d.getMonth()+1;   // Months are 0 based
          if (thisMonth < 10){
              thisMonth = "0"+thisMonth; // Leading 0
          }

          var thisDate = arg._d.getDate();
          if (thisDate < 10){
            thisDate = "0"+thisDate; // Leading 0
          }
          var thisYear = arg._d.getYear()+1900;   // Years are 1900 based

          var thisCompare = thisMonth +"/"+ thisDate +"/"+ thisYear;

          if($.inArray(thisCompare,disabledArr)!=-1){
            return arg._pf = {userInvalidated: true};
          }
      }
    });
  	newIDno = newIDno + 1;
  }

  addField();
  </script>
<style type="text/css">
  .navbar-wrapper .container{width: 100% !important;max-width:10000px;}
  .navbar-nav > li{
    display: inline-block !important;
  }
  .navbar-nav{
    display: inline-block;
  }
  .container > .navbar-header{
    position: fixed;
  }
  .disabled {
    background: #FDA2CC !important;
  }
</style>
{% endblock %}